# Type()

Чтобы узнать тип данных, вызывают функцию type() и передают ей имя переменной как аргумент: type(english)

## Вывод на одной строке End()

Ключ end (англ. end, «конец») сообщает, что печать нужно закончить не переносом (как это происходит по умолчанию), 
а, к примеру, пустой строкой:

In [ ]:
print('Анализ', end='')
print('эмодзи')

In [ ]:
print('Анализ ', end='')
print('эмодзи')

end — это именованный аргумент. Для него нужно указать не только значение, но и имя. 
Именованные аргументы придуманы для функций, у которых бывает много разных аргументов и опций, и без имён можно запутаться, что к чему относится. 
Обратите внимание, что вокруг знака = для именованных аргументов пробелы не ставят.

## Сортировка sort() метод списка

Сортировка обычных списков чисел. Для этого в Python существует функция sort()
Функция sort() прикреплена к типу данных list и выполняет свою работу над переменной этого типа. 
Такие функции называются методами.

In [ ]:
emojixpress = [
    2.26, 19.1, 25.6, 233.0, 15.2, 22.7, 64.6, 87.5, 6.81, 6.0,
    4.72, 24.7, 21.7, 10.0, 118.0, 3.31, 23.1, 1.74, 4.5, 0.0333
]

emojixpress.sort()

print(emojixpress)

In [ ]:
emoji_names = [
    'Ухмыляюсь', 'Сияю от радости', 'Катаюсь от смеха', 'Слёзы радости',
    'Подмигиваю', 'Счастлив', 'Глаза-сердца', 'Целую', 
    'Задумчивость', 'Равнодушие', 'Солнечные очки', 'Громко плачу', 
    'След от поцелуя', 'Два сердца', 'Сердце', 'Червы', 
    'Класс', 'Пожимаю плечами', 'Огонь', 'Переработка'
]
emoji_names.sort()

for name in emoji_names:

    print(name)

По умолчанию метод sort() упорядочивает список по возрастанию. Если мы хотим сортировать по убыванию, нужно указать это именованным аргументом reverse

Аргументу reverse присваивается значение True. Оно принадлежит к новому типу данных bool, который назван в честь Джорджа Буля (George Boole), создателя исчисления высказываний. Он придумал записывать логические утверждения символами. Для данных булевого типа возможно одно из двух значений: True (истина/верно/да, от англ. true, «истинный») либо False (ложь/неверно/нет, от англ. false, «ложный, фальшивый»). Выражение reverse=True на языке Python надо понимать так: да, сортировка действительно должна быть в обратном порядке. Если мы этого не напишем, Python по умолчанию сочтёт, что reverse=False, т.е. «нет, обратного порядка не нужно».

In [ ]:
twitter = [
    87.3, 150, 0.0, 2270.0, 264.0, 565.0, 834.0, 432.0, 0.0, 478.0, 
    198.0, 654.0, 98.7, 445.0, 1080.0, 697.0, 227.0, 0.0, 150.0, 932.0
]

twitter.sort(reverse=True)
for name in twitter:
    print(name)

## Добавление столбца append() метод списка

В каждый список-строку добавить новый элемент (соответствующий ячейке нового столбца). Для этого мы используем метод списка append() (англ. append, «добавить, присоединить»), добавляющий новый элемент в список. Разберём его сначала на простом примере:

In [ ]:
emoji = [
    'Ухмыляюсь', 'Сияю от радости', 'Катаюсь от смеха', 'Слёзы радости' 
]


print(emoji)

emoji.append('Подмигиваю')

print(emoji)

Метод append() добавляет свой аргумент в список как последний элемент.
Вызывая метод append() в цикле, можно добавить новый столбец. Попробуем для нашей таблицы: посчитаем долю использований каждого эмодзи из столбца «EmojiXpress, млн».

In [5]:
data = [
    ['Ухмыляюсь', 2.26, 1.02, 87.3],
    ['Сияю от радости', 19.1, 1.69, 150.0],
    ['Катаюсь от смеха', 25.6, 0.774, 0.0],
    ['Слёзы радости', 233.0, 7.31, 2270.0],
    ['Подмигиваю', 15.2, 2.36, 264.0],
    ['Счастлив', 22.7, 4.26, 565.0],
    ['Глаза-сердца', 64.6, 11.2, 834.0],
    ['Целую', 87.5, 5.13, 432.0],
    ['Задумчивость', 6.81, 0.636, 0.0],
    ['Равнодушие', 6.0, 0.236, 478.0],
    ['Солнечные очки', 4.72, 3.93, 198.0],
    ['Громко плачу', 24.7, 1.35, 654.0],
    ['След от поцелуя', 21.7, 2.87, 98.7],
    ['Два сердца', 10.0, 5.69, 445.0],
    ['Сердце', 118.0, 26.0, 1080.0],
    ['Червы', 3.31, 1.82, 697.0],
    ['Класс', 23.1, 3.75, 227.0],
    ['Пожимаю плечами', 1.74, 0.11, 0.0],
    ['Огонь', 4.5, 2.49, 150.0],
    ['Переработка', 0.0333, 0.056, 932.0]
]

emojixpress_total = 1720

for i in range(len(data)):
    # Для обращения к столбцу с индексом 1 в строке с индексом i
    # используется двойное обращение по индексу: data[i][1]
    # data[i] - строка с индексом i
    # data[i][1] - ее ячейка с индексом 1
    part = data[i][1] / emojixpress_total
    data[i].append(part)
    
    
print('Название эмодзи  | EmojiXpress, млн | EmojiXpress, доля')
print('-------------------------------------------------------')
for row in data:
    print('{: <16} | {: >16.2f} | {: >17.1%}'.format(row[0], row[1], row[4]))

Название эмодзи  | EmojiXpress, млн | EmojiXpress, доля
-------------------------------------------------------
Ухмыляюсь        |             2.26 |              0.1%
Сияю от радости  |            19.10 |              1.1%
Катаюсь от смеха |            25.60 |              1.5%
Слёзы радости    |           233.00 |             13.5%
Подмигиваю       |            15.20 |              0.9%
Счастлив         |            22.70 |              1.3%
Глаза-сердца     |            64.60 |              3.8%
Целую            |            87.50 |              5.1%
Задумчивость     |             6.81 |              0.4%
Равнодушие       |             6.00 |              0.3%
Солнечные очки   |             4.72 |              0.3%
Громко плачу     |            24.70 |              1.4%
След от поцелуя  |            21.70 |              1.3%
Два сердца       |            10.00 |              0.6%
Сердце           |           118.00 |              6.9%
Червы            |             3.31 |              0.2%
Класс            |            23.10 |              1.3%
Пожимаю плечами  |             1.74 |              0.1%
Огонь            |             4.50 |              0.3%
Переработка      |             0.03 |              0.0%

In [ ]:
#Добавьте в список названий emoji ещё три следующих элемента, используя метод append(). Выведите результат на экран.

emoji = [
    'Ухмыляюсь', 'Сияю от радости', 'Катаюсь от смеха', 
    'Слёзы радости', 'Подмигиваю'
]

emoji.append('Счастлив')
emoji.append('Глаза-сердца')
emoji.append('Целую')
# напишите код вместо многоточия
# < напишите код здесь >

print(emoji)

In [ ]:
#Создайте в таблице новый столбец: суммарное количество использований на всех платформах. 
#Отсортируйте таблицу по нему по убыванию и напечатайте на экране первые пять элементов. Вывод уже описан в коде:
data = [
    ['Ухмыляюсь', 2.26, 1.02, 87.3],
    ['Сияю от радости', 19.1, 1.69, 150.0],
    ['Катаюсь от смеха', 25.6, 0.774, 0.0],
    ['Слёзы радости', 233.0, 7.31, 2270.0],
    ['Подмигиваю', 15.2, 2.36, 264.0],
    ['Счастлив', 22.7, 4.26, 565.0],
    ['Глаза-сердца', 64.6, 11.2, 834.0],
    ['Целую', 87.5, 5.13, 432.0],
    ['Задумчивость', 6.81, 0.636, 0.0],
    ['Равнодушие', 6.0, 0.236, 478.0],
    ['Солнечные очки', 4.72, 3.93, 198.0],
    ['Громко плачу', 24.7, 1.35, 654.0],
    ['След от поцелуя', 21.7, 2.87, 98.7],
    ['Два сердца', 10.0, 5.69, 445.0],
    ['Сердце', 118.0, 26.0, 1080.0],
    ['Червы', 3.31, 1.82, 697.0],
    ['Класс', 23.1, 3.75, 227.0],
    ['Пожимаю плечами', 1.74, 0.11, 0.0],
    ['Огонь', 4.5, 2.49, 150.0],
    ['Переработка', 0.0333, 0.056, 932.0]
]

for i in range(len(data)):
    summa = data[i][1] + data[i][2] + data[i][3]
    data[i].append(summa)

for i in range(len(data)):
    data.sort(key=lambda row: row[4], reverse=True)
    
print('Название эмодзи  | Суммарное использование, млн')
print('-----------------------------------------------')
for row in data[:5]:
    print('{: <16} | {: >28.2f}'.format(row[0], row[4]))

In [ ]:
#Посчитайте средние значения для всех трёх платформ и сохраните их 
#в переменных emojixpress_mean, instagram_mean и twitter_mean соответственно (напомним: англ. mean, здесь в значении «средний»). 
#Напечатайте их значения на экране (см. код).
data = [
    ['Ухмыляюсь', 2.26, 1.02, 87.3],
    ['Сияю от радости', 19.1, 1.69, 150.0],
    ['Катаюсь от смеха', 25.6, 0.774, 0.0],
    ['Слёзы радости', 233.0, 7.31, 2270.0],
    ['Подмигиваю', 15.2, 2.36, 264.0],
    ['Счастлив', 22.7, 4.26, 565.0],
    ['Глаза-сердца', 64.6, 11.2, 834.0],
    ['Целую', 87.5, 5.13, 432.0],
    ['Задумчивость', 6.81, 0.636, 0.0],
    ['Равнодушие', 6.0, 0.236, 478.0],
    ['Солнечные очки', 4.72, 3.93, 198.0],
    ['Громко плачу', 24.7, 1.35, 654.0],
    ['След от поцелуя', 21.7, 2.87, 98.7],
    ['Два сердца', 10.0, 5.69, 445.0],
    ['Сердце', 118.0, 26.0, 1080.0],
    ['Червы', 3.31, 1.82, 697.0],
    ['Класс', 23.1, 3.75, 227.0],
    ['Пожимаю плечами', 1.74, 0.11, 0.0],
    ['Огонь', 4.5, 2.49, 150.0],
    ['Переработка', 0.0333, 0.056, 932.0]
]

emojixpress = [2.26, 19.1, 25.6, 233.0, 15.2, 22.7, 64.6, 87.5, 6.81, 6.0,
    4.72, 24.7, 21.7, 10.0, 118.0, 3.31, 23.1, 1.74, 4.5, 0.0333]

instagram = [1.02, 1.69, 0.774, 7.31, 2.36, 4.26, 11.2, 5.13, 0.636, 0.236, 3.93, 1.35, 2.87, 5.69, 26.0, 1.82, 3.75, 0.11, 2.49, 0.056]

twitter = [ 87.3, 150, 0.0, 2270.0, 264.0, 565.0, 834.0, 432.0, 0.0, 478.0, 
    198.0, 654.0, 98.7, 445.0, 1080.0, 697.0, 227.0, 0.0, 150.0, 932.0]

total_emojixpress = 0
for count in emojixpress:
    total_emojixpress += count

total_inst = 0
for count in instagram:
    total_inst += count
    
total_twit = 0
for count in twitter:
    total_twit += count

    emojixpress_mean = total_emojixpress / len(data)
    instagram_mean = total_inst / len(data)
    twitter_mean = total_twit / len(data)


print('Среднее для EmojiXpress: {:.2f}'.format(emojixpress_mean))
print('Среднее для Instagram: {:.2f}'.format(instagram_mean))
print('Среднее для Твиттера: {:.2f}'.format(twitter_mean))

In [ ]:
#Вычислите «индекс использования» для каждого эмодзи. Получившийся столбец с этими индексами добавьте к таблице.
data = [
    ['Ухмыляюсь', 2.26, 1.02, 87.3],
    ['Сияю от радости', 19.1, 1.69, 150.0],
    ['Катаюсь от смеха', 25.6, 0.774, 0.0],
    ['Слёзы радости', 233.0, 7.31, 2270.0],
    ['Подмигиваю', 15.2, 2.36, 264.0],
    ['Счастлив', 22.7, 4.26, 565.0],
    ['Глаза-сердца', 64.6, 11.2, 834.0],
    ['Целую', 87.5, 5.13, 432.0],
    ['Задумчивость', 6.81, 0.636, 0.0],
    ['Равнодушие', 6.0, 0.236, 478.0],
    ['Солнечные очки', 4.72, 3.93, 198.0],
    ['Громко плачу', 24.7, 1.35, 654.0],
    ['След от поцелуя', 21.7, 2.87, 98.7],
    ['Два сердца', 10.0, 5.69, 445.0],
    ['Сердце', 118.0, 26.0, 1080.0],
    ['Червы', 3.31, 1.82, 697.0],
    ['Класс', 23.1, 3.75, 227.0],
    ['Пожимаю плечами', 1.74, 0.11, 0.0],
    ['Огонь', 4.5, 2.49, 150.0],
    ['Переработка', 0.0333, 0.056, 932.0]
]

emojixpress_sum = 0
instagram_sum = 0
twitter_sum = 0
for row in data:
    emojixpress_sum += row[1]
    instagram_sum += row[2]
    twitter_sum += row[3]
    
emojixpress_mean = emojixpress_sum / len(data)
instagram_mean = instagram_sum / len(data)
twitter_mean = twitter_sum / len(data)

for i in range(len(data)):
    # Названия переменных выбраны, чтобы лучше отражать
    # их смысл. Normalized – от англ. "нормированный".
    emojixpress_normalized = data[i][1] / emojixpress_mean
    instagram_normalized = data[i][2] / instagram_mean
    twitter_normalized = data[i][3] / twitter_mean
    index = emojixpress_normalized + instagram_normalized + twitter_normalized
    data[i].append(index)
    
print('Название эмодзи  | Индекс использования')
print('---------------------------------------')
for row in data:
    print('{: <16} | {: >20.2f}'.format(row[0], row[4]))

In [ ]:
#Финальный шаг для получения отчёта: отсортируйте таблицу по новому столбцу и напечатайте на экране только первые пять элементов
data = [
    ['Ухмыляюсь', 2.26, 1.02, 87.3],
    ['Сияю от радости', 19.1, 1.69, 150.0],
    ['Катаюсь от смеха', 25.6, 0.774, 0.0],
    ['Слёзы радости', 233.0, 7.31, 2270.0],
    ['Подмигиваю', 15.2, 2.36, 264.0],
    ['Счастлив', 22.7, 4.26, 565.0],
    ['Глаза-сердца', 64.6, 11.2, 834.0],
    ['Целую', 87.5, 5.13, 432.0],
    ['Задумчивость', 6.81, 0.636, 0.0],
    ['Равнодушие', 6.0, 0.236, 478.0],
    ['Солнечные очки', 4.72, 3.93, 198.0],
    ['Громко плачу', 24.7, 1.35, 654.0],
    ['След от поцелуя', 21.7, 2.87, 98.7],
    ['Два сердца', 10.0, 5.69, 445.0],
    ['Сердце', 118.0, 26.0, 1080.0],
    ['Червы', 3.31, 1.82, 697.0],
    ['Класс', 23.1, 3.75, 227.0],
    ['Пожимаю плечами', 1.74, 0.11, 0.0],
    ['Огонь', 4.5, 2.49, 150.0],
    ['Переработка', 0.0333, 0.056, 932.0]
]

emojixpress_sum = 0
instagram_sum = 0
twitter_sum = 0
for row in data:
    emojixpress_sum += row[1]
    instagram_sum += row[2]
    twitter_sum += row[3]
    
emojixpress_mean = emojixpress_sum / len(data)
instagram_mean = instagram_sum / len(data)
twitter_mean = twitter_sum / len(data)

for i in range(len(data)):
    emojixpress_normalized = data[i][1] / emojixpress_mean
    instagram_normalized = data[i][2] / instagram_mean
    twitter_normalized = data[i][3] / twitter_mean
    index = emojixpress_normalized + instagram_normalized + twitter_normalized
    data[i].append(index)

data.sort(key=lambda row: row[1], reverse=True)

print('Название эмодзи  | Emojixpress, млн')
print('-----------------------------------')
for row in data[:5]:
    print('{: <16} | {: >16.2f}'.format(row[0], row[1]))
print()
print()

data.sort(key=lambda row: row[2], reverse=True)

print('Название эмодзи  | Instagram, млн')
print('---------------------------------')
for row in data[:5]:
    print('{: <16} | {: >14.2f}'.format(row[0], row[2]))
print()
print()

data.sort(key=lambda row: row[3], reverse=True)

print('Название эмодзи  | Твиттер, млн')
print('-------------------------------')
for row in data[:5]:
    print('{: <16} | {: >12.2f}'.format(row[0], row[3]))
print()
print()

data.sort(key=lambda row: row[4], reverse=True)

print('Название эмодзи  | Индекс использования')
print('---------------------------------------')
# обновите этот код
for row in data[:5]:
    print('{: <16} | {: >20.2f}'.format(row[0], row[4]))
print()

## Именнованный аргумент Key. Безымянная функция lambda

Python не считает наш список из списков таблицей. Он видит только перечень строк. Столбцов в этой таблице для Python не существует. Чтобы отсортировать таблицу по столбцу с индексом 1, нам нужно пояснить: считай, что последовательность для сортировки состоит из элементов каждой строки с индексом 1, и по этой последовательности сортируй. Это объяснение делается лямбда-функцией — короткой безымянной функцией

In [ ]:
lambda row: row[1]

Эта функция принимает на вход очередную строку row и возвращает столбец из элементов каждой строки с индексом 1. В нашем случае это записывается row[1]. Название row для очередных строк мы выбрали сами для наглядности, можете придумать и другое. Создавать полноценные собственные функции вы научитесь в следующей теме, а пока для сортировки годится простенькая лямбда-функция.

Именованные аргументы можно комбинировать. Например, давайте отсортируем данные столбца «EmojiXpress, млн» по убыванию, применяя одновременно key и reverse:

In [ ]:
data = [
    ['Ухмыляюсь', 2.26, 1.02, 87.3],
    ['Сияю от радости', 19.1, 1.69, 150.0],
    ['Катаюсь от смеха', 25.6, 0.774, 0.0],
    ['Слёзы радости', 233.0, 7.31, 2270.0],
    ['Подмигиваю', 15.2, 2.36, 264.0],
    ['Счастлив', 22.7, 4.26, 565.0],
    ['Глаза-сердца', 64.6, 11.2, 834.0],
    ['Целую', 87.5, 5.13, 432.0],
    ['Задумчивость', 6.81, 0.636, 0.0],
    ['Равнодушие', 6.0, 0.236, 478.0],
    ['Солнечные очки', 4.72, 3.93, 198.0],
    ['Громко плачу', 24.7, 1.35, 654.0],
    ['След от поцелуя', 21.7, 2.87, 98.7],
    ['Два сердца', 10.0, 5.69, 445.0],
    ['Сердце', 118.0, 26.0, 1080.0],
    ['Червы', 3.31, 1.82, 697.0],
    ['Класс', 23.1, 3.75, 227.0],
    ['Пожимаю плечами', 1.74, 0.11, 0.0],
    ['Огонь', 4.5, 2.49, 150.0],
    ['Переработка', 0.0333, 0.056, 932.0]
]

data.sort(key=lambda row: row[1], reverse=True)

print('Название эмодзи  | EmojiXpress, млн |', end='')
print(' Instagram, млн | Твиттер, млн')
print('-------------------------------------', end='')
print('------------------------------')
for row in data:
    print('{: <16} | {: >16.2f} | {: >14.2f} | {: >12.2f}'.format(
        row[0], row[1], row[2], row[3]))

## Срезы

Они похожи на индексы, но используются для обращения не к отдельным элементам, а к их диапазонам. Для среза указывают начало и конец диапазона:

In [ ]:
# англ. digit, "цифра", name, "название"
digits_names = [
    'ноль',
    'один',
    'два',
    'три',
    'четыре',
    'пять',
    'шесть',
    'семь',
    'восемь',
    'девять'
]

print(digits_names[4:7])

In [4]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "https://pictures.s3.yandex.net/resources/3_6_7_1564569409.png")

Первый индекс (в данном случае 4) будет включён в срез, а последний (в данном случае 7) — нет. Чтобы понять, почему разработчики Python так сделали, давайте представим плитку шоколада с нумерованными дольками. Срез 4:7 означает, что шоколадка ломается перед четвёртой долькой и перед седьмой.

Когда одна из границ диапазона совпадает с границей самого списка, эту границу можно вообще не указывать. Например, давайте напечатаем на экране первые несколько элементов двумя способами — с указанием начала списка (ноль) и без него.

In [ ]:
#digits_names = [
#    'ноль',
#    'один',
#    'два',
#    'три',
#    'четыре',
#    'пять',
#    'шесть',
#    'семь',
#    'восемь',
#    'девять'
#]

#print(digits_names[0:5])


digits_names = [
    'ноль',
    'один',
    'два',
    'три',
    'четыре',
    'пять',
    'шесть',
    'семь',
    'восемь',
    'девять'
]

print(digits_names[:5])

In [ ]:
digits_names = [
    'ноль',
    'один',
    'два',
    'три',
    'четыре',
    'пять',
    'шесть',
    'семь',
    'восемь',
    'девять'
]

print(digits_names[7:])

In [ ]:
data = [
    ['Ухмыляюсь', 2.26, 1.02, 87.3],
    ['Сияю от радости', 19.1, 1.69, 150.0],
    ['Катаюсь от смеха', 25.6, 0.774, 0.0],
    ['Слёзы радости', 233.0, 7.31, 2270.0],
    ['Подмигиваю', 15.2, 2.36, 264.0],
    ['Счастлив', 22.7, 4.26, 565.0],
    ['Глаза-сердца', 64.6, 11.2, 834.0],
    ['Целую', 87.5, 5.13, 432.0],
    ['Задумчивость', 6.81, 0.636, 0.0],
    ['Равнодушие', 6.0, 0.236, 478.0],
    ['Солнечные очки', 4.72, 3.93, 198.0],
    ['Громко плачу', 24.7, 1.35, 654.0],
    ['След от поцелуя', 21.7, 2.87, 98.7],
    ['Два сердца', 10.0, 5.69, 445.0],
    ['Сердце', 118.0, 26.0, 1080.0],
    ['Червы', 3.31, 1.82, 697.0],
    ['Класс', 23.1, 3.75, 227.0],
    ['Пожимаю плечами', 1.74, 0.11, 0.0],
    ['Огонь', 4.5, 2.49, 150.0],
    ['Переработка', 0.0333, 0.056, 932.0]
]

data.sort(key=lambda row: row[1], reverse=True)

# мы оставили только тот столбец, по которому сортировали
print('Название эмодзи  | Emojixpress, млн')
print('-----------------------------------')
for row in data[:5]:
    print('{: <16} | {: >16.2f}'.format(row[0], row[1]))
print()
print()
    
data.sort(key=lambda row: row[2], reverse=True)

# мы оставили только тот столбец, по которому сортировали
print('Название эмодзи  | Instagram, млн')
print('---------------------------------')
for row in data[:5]:
    print('{: <16} | {: >14.2f}'.format(row[0], row[2]))
print()
print()
    
data.sort(key=lambda row: row[3], reverse=True)

# мы оставили только тот столбец, по которому сортировали
print('Название эмодзи  | Твиттер, млн')
print('-------------------------------')
for row in data[:5]:
    print('{: <16} | {: >12.2f}'.format(row[0], row[3]))
print()
print()

## Функция Format() строковый метод

In [ ]:
chinese_speakers = 1107
print('Число людей, говорящих на китайском: {} млн'.format(chinese_speakers))

Разберём этот код по частям. Сначала пишется шаблон строки, которую мы хотим напечатать, где каждое число заменено фигурными скобками {}. Потом ставится точка и слово format. В круглых скобках функции format() передаются аргументы — список чисел, подставляемых вместо фигурных скобок.

In [1]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "https://pictures.s3.yandex.net/resources/1_16_4_1564568566.png")

Пока фигурные скобки пустые, число выводится так, как оно хранится в переменной. Но в этих фигурных скобках можно задать шаблон вывода. Он может оговаривать нужное количество знаков после запятой:

In [ ]:
english_web_part = 0.539
print('Доля сайтов с английским языком: {:.2f}'.format(english_web_part))

Группа символов {:.2f} означает, что после запятой должно идти два знака. Последний символ "f" происходит от слова fixed (англ. «фиксированный») и означает, что число выводится как десятичная дробь с фиксированной точностью. Если же в конце поставить знак процента, то format() выведет не число, а процент:

In [ ]:
english_web_part = 0.539
print('Доля сайтов с английским языком: {:.2%}'.format(english_web_part))

In [ ]:
total_web = 10
total_speakers = 7539

chinese_speakers = 1107
chinese_web_part = 0.017

chinese_speakers_part = chinese_speakers / total_speakers
print('Доля людей, говорящих на китайском: {:.2f}'.format(chinese_speakers_part)) # напишите код вместо многоточия

In [ ]:
total_web = 10
total_speakers = 7539

chinese_speakers = 1107
chinese_web_part = 0.017

english_speakers = 1121
english_web_part = 0.539

russian_speakers = 264.3
russian_web_part = 0.061

chinese_speakers_part = chinese_speakers / total_speakers
print('Доля людей, говорящих на китайском: {:.1%}'.format(chinese_speakers_part)) # напишите код вместо многоточия
 
english_speakers_part = english_speakers / total_speakers
print('Доля людей, говорящих на английском: {:.1%}'.format(english_speakers_part))

russian_speakers_part = russian_speakers / total_speakers
print('Доля людей, говорящих на русском: {:.1%}'.format(russian_speakers_part))

## Оператор in

Поле «Жанр» в нашей таблице имеет тип list. Давайте разберёмся, как фильтровать таблицу по нему.
Дело в том, что поле с типом list содержит несколько значений, а значит, математические проверки не пройдут. Для такого случая в Python есть специальный оператор: in (англ. in, «в»):

In [ ]:
print('драма' in ['фантастика', 'драма'])
print('комедия' in ['драма', 'криминал', 'история'])

Такую конструкцию нужно читать: “элемент «драма» есть в списке: «фантастика», «драма»”.
Это утверждение может быть истинным или ложным, то есть — принимать значение True или False. Таким образом, оператор in удобен в условных конструкциях:

In [ ]:
birdman_genres = ['драма', 'комедия']
if 'криминал' in birdman_genres:
    print('Фильм "Бёрдмэн" содержит жанр "криминал"')
else:
    print('Фильм "Бёрдмэн" не содержит жанр "криминал"')

In [ ]:
#Отфильтруем же таблицу по жанру! Для этой цели напишите функцию filter_by_genre() (англ. filter by genre, «фильтровать по жанру»).
#Она должна иметь два аргумента: таблицу с данными и название жанра. 
#А возвращать — новую таблицу с фильмами переданного жанра.
oscar_data = [
    ['Форма воды', 2017, 6.914, 123, ['фантастика', 'драма'], 19.4, 195.243464],
    ['Лунный свет', 2016, 6.151, 110, ['драма'], 1.5, 65.046687],
    ['В центре внимания', 2015, 7.489, 129, ['драма', 'криминал', 'история'], 20.0, 88.346473],
    ['Бёрдмэн', 2014, 7.604, 119, ['драма', 'комедия'], 18.0, 103.215094],
    ['12 лет рабства', 2013, 7.71, 133, ['драма', 'биография', 'история'], 20.0, 178.371993],
    ['Операция "Арго"', 2012, 7.517, 120, ['триллер', 'драма', 'биография'], 44.5, 232.324128],
    ['Артист', 2011, 7.942, 96, ['драма', 'мелодрама', 'комедия'], 15.0, 133.432856],
    ['Король говорит!', 2010, 7.977, 118, ['драма', 'биография', 'история'], 15.0, 414.211549],
    ['Повелитель бури', 2008, 7.298, 126, ['триллер', 'драма', 'военный', 'история'], 15.0, 49.230772],
    ['Миллионер из трущоб', 2008, 7.724, 120, ['драма', 'мелодрама'], 15.0, 377.910544],
    ['Старикам тут не место', 2007, 7.726, 122, ['триллер', 'драма', 'криминал'], 25.0, 171.627166],
    ['Отступники', 2006, 8.456, 151, ['триллер', 'драма', 'криминал'], 90.0, 289.847354],
    ['Столкновение', 2004, 7.896, 108, ['триллер', 'драма', 'криминал'], 6.5, 98.410061],
    ['Малышка на миллион', 2004, 8.075, 132, ['драма', 'спорт'], 30.0, 216.763646],
    ['Властелин колец: Возвращение Короля', 2003, 8.617, 201, ['фэнтези', 'драма', 'приключения'], 94.0, 1119.110941],
    ['Чикаго', 2002, 7.669, 113, ['мюзикл', 'комедия', 'криминал'], 45.0, 306.776732],
    ['Игры разума', 2001, 8.557, 135, ['драма', 'биография', 'мелодрама'], 58.0, 313.542341],
    ['Гладиатор', 2000, 8.585, 155, ['боевик', 'драма', 'приключения'], 103.0, 457.640427],
    ['Красота по-американски', 1999, 7.965, 122, ['драма'], 15.0, 356.296601],
    ['Влюбленный Шекспир', 1998, 7.452, 123, ['драма', 'мелодрама', 'комедия', 'история'], 25.0, 289.317794],
    ['Титаник', 1997, 8.369, 194, ['драма', 'мелодрама'], 200.0, 2185.372302],
    ['Английский пациент', 1996, 7.849, 155, ['драма', 'мелодрама', 'военный'], 27.0, 231.976425],
    ['Храброе сердце', 1995, 8.283, 178, ['драма', 'военный', 'биография', 'история'], 72.0, 210.409945],
    ['Форрест Гамп', 1994, 8.915, 142, ['драма', 'мелодрама'], 55.0, 677.386686],
    ['Список Шиндлера', 1993, 8.819, 195, ['драма', 'биография', 'история'], 22.0, 321.265768],
    ['Непрощенный', 1992, 7.858, 131, ['драма', 'вестерн'], 14.4, 159.157447],
    ['Молчание ягнят', 1990, 8.335, 114, ['триллер', 'криминал', 'детектив', 'драма', 'ужасы'], 19.0, 272.742922],
    ['Танцующий с волками', 1990, 8.112, 181, ['драма', 'приключения', 'вестерн'], 22.0, 424.208848],
    ['Шофёр мисс Дэйзи', 1989, 7.645, 99, ['драма'], 7.5, 145.793296],
    ['Человек дождя', 1988, 8.25, 133, ['драма'], 25.0, 354.825435],
]

def filter_by_genre(data, genre):
    result = []
    for row in data:
        genres = row[4]
        if genre in genres:
            result.append(row)
    return result

def print_table(data):
    print('Название                            | Год  | Рейтинг | Длина | Бюджет | Сборы  |')
    print('--------------------------------------------------------------------------------')
    for row in data:
        print('{: <35} | {} | {: >7.2f} | {: >5} | {: >6.1f} | {: >6.1f} |'.format(
            row[0], row[1], row[2], row[3], row[5], row[6]))

filtered_data = filter_by_genre(oscar_data, "мелодрама")
print_table(filtered_data)

In [ ]:
#Одни жанры встречаются чаще других. Давайте найдём самые популярные. 
#Создайте таблицу и сохраните её в переменной genres_counts (англ. genres counts, «счётчики жанров»). 
#Она должна состоять из двух столбцов: «название жанра» и «количество фильмов с ним».
#Все жанры мы собрали в переменной all_genres (англ. all genres, «все жанры»). 

oscar_data = [
    ['Форма воды', 2017, 6.914, 123, ['фантастика', 'драма'], 19.4, 195.243464],
    ['Лунный свет', 2016, 6.151, 110, ['драма'], 1.5, 65.046687],
    ['В центре внимания', 2015, 7.489, 129, ['драма', 'криминал', 'история'], 20.0, 88.346473],
    ['Бёрдмэн', 2014, 7.604, 119, ['драма', 'комедия'], 18.0, 103.215094],
    ['12 лет рабства', 2013, 7.71, 133, ['драма', 'биография', 'история'], 20.0, 178.371993],
    ['Операция "Арго"', 2012, 7.517, 120, ['триллер', 'драма', 'биография'], 44.5, 232.324128],
    ['Артист', 2011, 7.942, 96, ['драма', 'мелодрама', 'комедия'], 15.0, 133.432856],
    ['Король говорит!', 2010, 7.977, 118, ['драма', 'биография', 'история'], 15.0, 414.211549],
    ['Повелитель бури', 2008, 7.298, 126, ['триллер', 'драма', 'военный', 'история'], 15.0, 49.230772],
    ['Миллионер из трущоб', 2008, 7.724, 120, ['драма', 'мелодрама'], 15.0, 377.910544],
    ['Старикам тут не место', 2007, 7.726, 122, ['триллер', 'драма', 'криминал'], 25.0, 171.627166],
    ['Отступники', 2006, 8.456, 151, ['триллер', 'драма', 'криминал'], 90.0, 289.847354],
    ['Столкновение', 2004, 7.896, 108, ['триллер', 'драма', 'криминал'], 6.5, 98.410061],
    ['Малышка на миллион', 2004, 8.075, 132, ['драма', 'спорт'], 30.0, 216.763646],
    ['Властелин колец: Возвращение Короля', 2003, 8.617, 201, ['фэнтези', 'драма', 'приключения'], 94.0, 1119.110941],
    ['Чикаго', 2002, 7.669, 113, ['мюзикл', 'комедия', 'криминал'], 45.0, 306.776732],
    ['Игры разума', 2001, 8.557, 135, ['драма', 'биография', 'мелодрама'], 58.0, 313.542341],
    ['Гладиатор', 2000, 8.585, 155, ['боевик', 'драма', 'приключения'], 103.0, 457.640427],
    ['Красота по-американски', 1999, 7.965, 122, ['драма'], 15.0, 356.296601],
    ['Влюбленный Шекспир', 1998, 7.452, 123, ['драма', 'мелодрама', 'комедия', 'история'], 25.0, 289.317794],
    ['Титаник', 1997, 8.369, 194, ['драма', 'мелодрама'], 200.0, 2185.372302],
    ['Английский пациент', 1996, 7.849, 155, ['драма', 'мелодрама', 'военный'], 27.0, 231.976425],
    ['Храброе сердце', 1995, 8.283, 178, ['драма', 'военный', 'биография', 'история'], 72.0, 210.409945],
    ['Форрест Гамп', 1994, 8.915, 142, ['драма', 'мелодрама'], 55.0, 677.386686],
    ['Список Шиндлера', 1993, 8.819, 195, ['драма', 'биография', 'история'], 22.0, 321.265768],
    ['Непрощенный', 1992, 7.858, 131, ['драма', 'вестерн'], 14.4, 159.157447],
    ['Молчание ягнят', 1990, 8.335, 114, ['триллер', 'криминал', 'детектив', 'драма', 'ужасы'], 19.0, 272.742922],
    ['Танцующий с волками', 1990, 8.112, 181, ['драма', 'приключения', 'вестерн'], 22.0, 424.208848],
    ['Шофёр мисс Дэйзи', 1989, 7.645, 99, ['драма'], 7.5, 145.793296],
    ['Человек дождя', 1988, 8.25, 133, ['драма'], 25.0, 354.825435],
]

# функция для фильтрации таблицы по жанрам
def filter_by_genre(data, genre):
    result = []
    for row in data:
        genres = row[4]
        if genre in genres:
            result.append(row)
    return result

all_genres = [
    'фантастика', 'драма', 'криминал', 'история', 'комедия', 'биография',
    'триллер', 'военный', 'мелодрама', 'боевик', 'приключения', 'вестерн',
    'детектив', 'ужасы'
]

# Создайте таблицу (список списков) со столбцами 
# "название жанра" и "количество фильмов с ним".
# Назовите переменную genres_counts.
genres_counts = []
for genre in all_genres:
    # отфильтруйте таблицу по жанру genre
    # используйте для этого функцию filter_by_genre()
    filtered_data = filter_by_genre(oscar_data, genre)

    # подсчитайте длину отфильтрованной таблицы
    # используйте для этого функцию len()
    count = len(filtered_data)
    
    # добавьте название жанра и результат подсчёта в таблицу
    # используйте для этого функцию append()
    genres_counts.append([genre, count])

# отсортируйте таблицу по убыванию количества
# используйте для этого функцию sort()
genres_counts.sort(key=lambda row: row[1], reverse=True)

print('Жанр        | Количество')
print('------------------------')
for row in genres_counts:
    genre = row[0]
    count = row[1]
    print('{: <11} | {: >10}'.format(genre, count))

## Оператор not

Оператор not переворачивает любое условие с ног на голову — меняет True на False и наоборот:

In [ ]:
def check_if_recent(year):
    if not year > 2007:
        print('Фильм был снят давно.')
    else:
        print('Фильм свежий.')

In [ ]:
#Допишите функцию filter_without_genre() (от англ. filter without a genre, в значении «отфильтруй фильмы, не относящиеся к жанру»). 
#Она должна выкидывать из таблицы все фильмы заданного жанра. 
#Аргументы этой функции: таблица с фильмами и жанр, который нужно исключить.
oscar_data = [
    ['Форма воды', 2017, 6.914, 123, ['фантастика', 'драма'], 19.4, 195.243464],
    ['Лунный свет', 2016, 6.151, 110, ['драма'], 1.5, 65.046687],
    ['В центре внимания', 2015, 7.489, 129, ['драма', 'криминал', 'история'], 20.0, 88.346473],
    ['Бёрдмэн', 2014, 7.604, 119, ['драма', 'комедия'], 18.0, 103.215094],
    ['12 лет рабства', 2013, 7.71, 133, ['драма', 'биография', 'история'], 20.0, 178.371993],
    ['Операция "Арго"', 2012, 7.517, 120, ['триллер', 'драма', 'биография'], 44.5, 232.324128],
    ['Артист', 2011, 7.942, 96, ['драма', 'мелодрама', 'комедия'], 15.0, 133.432856],
    ['Король говорит!', 2010, 7.977, 118, ['драма', 'биография', 'история'], 15.0, 414.211549],
    ['Повелитель бури', 2008, 7.298, 126, ['триллер', 'драма', 'военный', 'история'], 15.0, 49.230772],
    ['Миллионер из трущоб', 2008, 7.724, 120, ['драма', 'мелодрама'], 15.0, 377.910544],
    ['Старикам тут не место', 2007, 7.726, 122, ['триллер', 'драма', 'криминал'], 25.0, 171.627166],
    ['Отступники', 2006, 8.456, 151, ['триллер', 'драма', 'криминал'], 90.0, 289.847354],
    ['Столкновение', 2004, 7.896, 108, ['триллер', 'драма', 'криминал'], 6.5, 98.410061],
    ['Малышка на миллион', 2004, 8.075, 132, ['драма', 'спорт'], 30.0, 216.763646],
    ['Властелин колец: Возвращение Короля', 2003, 8.617, 201, ['фэнтези', 'драма', 'приключения'], 94.0, 1119.110941],
    ['Чикаго', 2002, 7.669, 113, ['мюзикл', 'комедия', 'криминал'], 45.0, 306.776732],
    ['Игры разума', 2001, 8.557, 135, ['драма', 'биография', 'мелодрама'], 58.0, 313.542341],
    ['Гладиатор', 2000, 8.585, 155, ['боевик', 'драма', 'приключения'], 103.0, 457.640427],
    ['Красота по-американски', 1999, 7.965, 122, ['драма'], 15.0, 356.296601],
    ['Влюбленный Шекспир', 1998, 7.452, 123, ['драма', 'мелодрама', 'комедия', 'история'], 25.0, 289.317794],
    ['Титаник', 1997, 8.369, 194, ['драма', 'мелодрама'], 200.0, 2185.372302],
    ['Английский пациент', 1996, 7.849, 155, ['драма', 'мелодрама', 'военный'], 27.0, 231.976425],
    ['Храброе сердце', 1995, 8.283, 178, ['драма', 'военный', 'биография', 'история'], 72.0, 210.409945],
    ['Форрест Гамп', 1994, 8.915, 142, ['драма', 'мелодрама'], 55.0, 677.386686],
    ['Список Шиндлера', 1993, 8.819, 195, ['драма', 'биография', 'история'], 22.0, 321.265768],
    ['Непрощенный', 1992, 7.858, 131, ['драма', 'вестерн'], 14.4, 159.157447],
    ['Молчание ягнят', 1990, 8.335, 114, ['триллер', 'криминал', 'детектив', 'драма', 'ужасы'], 19.0, 272.742922],
    ['Танцующий с волками', 1990, 8.112, 181, ['драма', 'приключения', 'вестерн'], 22.0, 424.208848],
    ['Шофёр мисс Дэйзи', 1989, 7.645, 99, ['драма'], 7.5, 145.793296],
    ['Человек дождя', 1988, 8.25, 133, ['драма'], 25.0, 354.825435],
]


def filter_without_genre(data, genre):
    result = []
    for row in data:
        genres = row[4]
        if not genre in genres:
            result.append(row)
    return result


def print_table(data):
    print('Название                            | Год  | Рейтинг | Длина | Бюджет | Сборы  |')
    print('--------------------------------------------------------------------------------')
    for row in data:
        print('{: <35} | {} | {: >7.2f} | {: >5} | {: >6.1f} | {: >6.1f} |'.format(
            row[0], row[1], row[2], row[3], row[5], row[6]))
        
filtered_data = filter_without_genre(oscar_data, 'драма')
print_table(filtered_data)

## Оператор And & Or

Оператор and объединяет два условия в одно. Такое составное условие возвращает True только тогда, когда выполнены оба простых условия:

In [ ]:
print(True and True)
print(True and False)
print(False and True)
print(False and False)

In [ ]:
oscar_data = [
    ['Форма воды', 2017, 6.914, 123, ['фантастика', 'драма'], 19.4, 195.243464],
    ['Лунный свет', 2016, 6.151, 110, ['драма'], 1.5, 65.046687],
    ['В центре внимания', 2015, 7.489, 129, ['драма', 'криминал', 'история'], 20.0, 88.346473],
    ['Бёрдмэн', 2014, 7.604, 119, ['драма', 'комедия'], 18.0, 103.215094],
    ['12 лет рабства', 2013, 7.71, 133, ['драма', 'биография', 'история'], 20.0, 178.371993],
    ['Операция "Арго"', 2012, 7.517, 120, ['триллер', 'драма', 'биография'], 44.5, 232.324128],
    ['Артист', 2011, 7.942, 96, ['драма', 'мелодрама', 'комедия'], 15.0, 133.432856],
    ['Король говорит!', 2010, 7.977, 118, ['драма', 'биография', 'история'], 15.0, 414.211549],
    ['Повелитель бури', 2008, 7.298, 126, ['триллер', 'драма', 'военный', 'история'], 15.0, 49.230772],
    ['Миллионер из трущоб', 2008, 7.724, 120, ['драма', 'мелодрама'], 15.0, 377.910544],
    ['Старикам тут не место', 2007, 7.726, 122, ['триллер', 'драма', 'криминал'], 25.0, 171.627166],
    ['Отступники', 2006, 8.456, 151, ['триллер', 'драма', 'криминал'], 90.0, 289.847354],
    ['Столкновение', 2004, 7.896, 108, ['триллер', 'драма', 'криминал'], 6.5, 98.410061],
    ['Малышка на миллион', 2004, 8.075, 132, ['драма', 'спорт'], 30.0, 216.763646],
    ['Властелин колец: Возвращение Короля', 2003, 8.617, 201, ['фэнтези', 'драма', 'приключения'], 94.0, 1119.110941],
    ['Чикаго', 2002, 7.669, 113, ['мюзикл', 'комедия', 'криминал'], 45.0, 306.776732],
    ['Игры разума', 2001, 8.557, 135, ['драма', 'биография', 'мелодрама'], 58.0, 313.542341],
    ['Гладиатор', 2000, 8.585, 155, ['боевик', 'драма', 'приключения'], 103.0, 457.640427],
    ['Красота по-американски', 1999, 7.965, 122, ['драма'], 15.0, 356.296601],
    ['Влюбленный Шекспир', 1998, 7.452, 123, ['драма', 'мелодрама', 'комедия', 'история'], 25.0, 289.317794],
    ['Титаник', 1997, 8.369, 194, ['драма', 'мелодрама'], 200.0, 2185.372302],
    ['Английский пациент', 1996, 7.849, 155, ['драма', 'мелодрама', 'военный'], 27.0, 231.976425],
    ['Храброе сердце', 1995, 8.283, 178, ['драма', 'военный', 'биография', 'история'], 72.0, 210.409945],
    ['Форрест Гамп', 1994, 8.915, 142, ['драма', 'мелодрама'], 55.0, 677.386686],
    ['Список Шиндлера', 1993, 8.819, 195, ['драма', 'биография', 'история'], 22.0, 321.265768],
    ['Непрощенный', 1992, 7.858, 131, ['драма', 'вестерн'], 14.4, 159.157447],
    ['Молчание ягнят', 1990, 8.335, 114, ['триллер', 'криминал', 'детектив', 'драма', 'ужасы'], 19.0, 272.742922],
    ['Танцующий с волками', 1990, 8.112, 181, ['драма', 'приключения', 'вестерн'], 22.0, 424.208848],
    ['Шофёр мисс Дэйзи', 1989, 7.645, 99, ['драма'], 7.5, 145.793296],
    ['Человек дождя', 1988, 8.25, 133, ['драма'], 25.0, 354.825435],
]

def filter_new_historic(data):
    result = []
    for row in data:
        year = row[1]
        genres = row[4]
        if year > 2000 and 'история' in genres:
            result.append(row)
    return result


def print_table(data):
    print('Название                            | Год  | Рейтинг | Длина | Бюджет | Сборы  |')
    print('--------------------------------------------------------------------------------')
    for row in data:
        print('{: <35} | {} | {: >7.2f} | {: >5} | {: >6.1f} | {: >6.1f} |'.format(
            row[0], row[1], row[2], row[3], row[5], row[6]))
        
filtered_data = filter_new_historic(oscar_data)
print_table(filtered_data)

Оператор or тоже объединяет два условия в одно. Такое составное условие возвращает True, если выполнено хотя бы одно из простых условий:

In [ ]:
print(True or True)
print(True or False)
print(False or True)
print(False or False)

In [ ]:
oscar_data = [
    ['Форма воды', 2017, 6.914, 123, ['фантастика', 'драма'], 19.4, 195.243464],
    ['Лунный свет', 2016, 6.151, 110, ['драма'], 1.5, 65.046687],
    ['В центре внимания', 2015, 7.489, 129, ['драма', 'криминал', 'история'], 20.0, 88.346473],
    ['Бёрдмэн', 2014, 7.604, 119, ['драма', 'комедия'], 18.0, 103.215094],
    ['12 лет рабства', 2013, 7.71, 133, ['драма', 'биография', 'история'], 20.0, 178.371993],
    ['Операция "Арго"', 2012, 7.517, 120, ['триллер', 'драма', 'биография'], 44.5, 232.324128],
    ['Артист', 2011, 7.942, 96, ['драма', 'мелодрама', 'комедия'], 15.0, 133.432856],
    ['Король говорит!', 2010, 7.977, 118, ['драма', 'биография', 'история'], 15.0, 414.211549],
    ['Повелитель бури', 2008, 7.298, 126, ['триллер', 'драма', 'военный', 'история'], 15.0, 49.230772],
    ['Миллионер из трущоб', 2008, 7.724, 120, ['драма', 'мелодрама'], 15.0, 377.910544],
    ['Старикам тут не место', 2007, 7.726, 122, ['триллер', 'драма', 'криминал'], 25.0, 171.627166],
    ['Отступники', 2006, 8.456, 151, ['триллер', 'драма', 'криминал'], 90.0, 289.847354],
    ['Столкновение', 2004, 7.896, 108, ['триллер', 'драма', 'криминал'], 6.5, 98.410061],
    ['Малышка на миллион', 2004, 8.075, 132, ['драма', 'спорт'], 30.0, 216.763646],
    ['Властелин колец: Возвращение Короля', 2003, 8.617, 201, ['фэнтези', 'драма', 'приключения'], 94.0, 1119.110941],
    ['Чикаго', 2002, 7.669, 113, ['мюзикл', 'комедия', 'криминал'], 45.0, 306.776732],
    ['Игры разума', 2001, 8.557, 135, ['драма', 'биография', 'мелодрама'], 58.0, 313.542341],
    ['Гладиатор', 2000, 8.585, 155, ['боевик', 'драма', 'приключения'], 103.0, 457.640427],
    ['Красота по-американски', 1999, 7.965, 122, ['драма'], 15.0, 356.296601],
    ['Влюбленный Шекспир', 1998, 7.452, 123, ['драма', 'мелодрама', 'комедия', 'история'], 25.0, 289.317794],
    ['Титаник', 1997, 8.369, 194, ['драма', 'мелодрама'], 200.0, 2185.372302],
    ['Английский пациент', 1996, 7.849, 155, ['драма', 'мелодрама', 'военный'], 27.0, 231.976425],
    ['Храброе сердце', 1995, 8.283, 178, ['драма', 'военный', 'биография', 'история'], 72.0, 210.409945],
    ['Форрест Гамп', 1994, 8.915, 142, ['драма', 'мелодрама'], 55.0, 677.386686],
    ['Список Шиндлера', 1993, 8.819, 195, ['драма', 'биография', 'история'], 22.0, 321.265768],
    ['Непрощенный', 1992, 7.858, 131, ['драма', 'вестерн'], 14.4, 159.157447],
    ['Молчание ягнят', 1990, 8.335, 114, ['триллер', 'криминал', 'детектив', 'драма', 'ужасы'], 19.0, 272.742922],
    ['Танцующий с волками', 1990, 8.112, 181, ['драма', 'приключения', 'вестерн'], 22.0, 424.208848],
    ['Шофёр мисс Дэйзи', 1989, 7.645, 99, ['драма'], 7.5, 145.793296],
    ['Человек дождя', 1988, 8.25, 133, ['драма'], 25.0, 354.825435],
]

def filter_fantastic(data):
    result = []
    for row in data:
        genres = row[4]
        if 'фантастика' in genres or 'фэнтези' in genres:
            result.append(row)
    return result


def print_table(data):
    print('Название                            | Год  | Рейтинг | Длина | Бюджет | Сборы  |')
    print('--------------------------------------------------------------------------------')
    for row in data:
        print('{: <35} | {} | {: >7.2f} | {: >5} | {: >6.1f} | {: >6.1f} |'.format(
            row[0], row[1], row[2], row[3], row[5], row[6]))
        
filtered_data = filter_fantastic(oscar_data)
print_table(filtered_data)

In [ ]:
#Напишите функцию filter_suspense() (англ. filter suspense, «отобрать напряжённое»), 
#которая находит фильмы самых напряжённых жанров: «триллер» и «ужасы». 
#Функция должна принимать как аргумент исходную таблицу и, не меняя её, возвращать отфильтрованную.

oscar_data = [
    ['Форма воды', 2017, 6.914, 123, ['фантастика', 'драма'], 19.4, 195.243464],
    ['Лунный свет', 2016, 6.151, 110, ['драма'], 1.5, 65.046687],
    ['В центре внимания', 2015, 7.489, 129, ['драма', 'криминал', 'история'], 20.0, 88.346473],
    ['Бёрдмэн', 2014, 7.604, 119, ['драма', 'комедия'], 18.0, 103.215094],
    ['12 лет рабства', 2013, 7.71, 133, ['драма', 'биография', 'история'], 20.0, 178.371993],
    ['Операция "Арго"', 2012, 7.517, 120, ['триллер', 'драма', 'биография'], 44.5, 232.324128],
    ['Артист', 2011, 7.942, 96, ['драма', 'мелодрама', 'комедия'], 15.0, 133.432856],
    ['Король говорит!', 2010, 7.977, 118, ['драма', 'биография', 'история'], 15.0, 414.211549],
    ['Повелитель бури', 2008, 7.298, 126, ['триллер', 'драма', 'военный', 'история'], 15.0, 49.230772],
    ['Миллионер из трущоб', 2008, 7.724, 120, ['драма', 'мелодрама'], 15.0, 377.910544],
    ['Старикам тут не место', 2007, 7.726, 122, ['триллер', 'драма', 'криминал'], 25.0, 171.627166],
    ['Отступники', 2006, 8.456, 151, ['триллер', 'драма', 'криминал'], 90.0, 289.847354],
    ['Столкновение', 2004, 7.896, 108, ['триллер', 'драма', 'криминал'], 6.5, 98.410061],
    ['Малышка на миллион', 2004, 8.075, 132, ['драма', 'спорт'], 30.0, 216.763646],
    ['Властелин колец: Возвращение Короля', 2003, 8.617, 201, ['фэнтези', 'драма', 'приключения'], 94.0, 1119.110941],
    ['Чикаго', 2002, 7.669, 113, ['мюзикл', 'комедия', 'криминал'], 45.0, 306.776732],
    ['Игры разума', 2001, 8.557, 135, ['драма', 'биография', 'мелодрама'], 58.0, 313.542341],
    ['Гладиатор', 2000, 8.585, 155, ['боевик', 'драма', 'приключения'], 103.0, 457.640427],
    ['Красота по-американски', 1999, 7.965, 122, ['драма'], 15.0, 356.296601],
    ['Влюбленный Шекспир', 1998, 7.452, 123, ['драма', 'мелодрама', 'комедия', 'история'], 25.0, 289.317794],
    ['Титаник', 1997, 8.369, 194, ['драма', 'мелодрама'], 200.0, 2185.372302],
    ['Английский пациент', 1996, 7.849, 155, ['драма', 'мелодрама', 'военный'], 27.0, 231.976425],
    ['Храброе сердце', 1995, 8.283, 178, ['драма', 'военный', 'биография', 'история'], 72.0, 210.409945],
    ['Форрест Гамп', 1994, 8.915, 142, ['драма', 'мелодрама'], 55.0, 677.386686],
    ['Список Шиндлера', 1993, 8.819, 195, ['драма', 'биография', 'история'], 22.0, 321.265768],
    ['Непрощенный', 1992, 7.858, 131, ['драма', 'вестерн'], 14.4, 159.157447],
    ['Молчание ягнят', 1990, 8.335, 114, ['триллер', 'криминал', 'детектив', 'драма', 'ужасы'], 19.0, 272.742922],
    ['Танцующий с волками', 1990, 8.112, 181, ['драма', 'приключения', 'вестерн'], 22.0, 424.208848],
    ['Шофёр мисс Дэйзи', 1989, 7.645, 99, ['драма'], 7.5, 145.793296],
    ['Человек дождя', 1988, 8.25, 133, ['драма'], 25.0, 354.825435],
]

def filter_suspense(data):
    result = []
    for row in data:
        genres = row[4]
        if 'триллер' in genres or 'ужасы' in genres:
            result.append(row)
    return result



def print_table(data):
    print('Название                            | Год  | Рейтинг | Длина | Бюджет | Сборы  |')
    print('--------------------------------------------------------------------------------')
    for row in data:
        print('{: <35} | {} | {: >7.2f} | {: >5} | {: >6.1f} | {: >6.1f} |'.format(
            row[0], row[1], row[2], row[3], row[5], row[6]))
        
filtered_data = filter_suspense(oscar_data)
print_table(filtered_data)

In [ ]:
#Для анализа фильмов по годам нам нужно научиться выделять из таблицы диапазоны: например с 2000 по 2010 год. 
#Напишите функцию filter_first_decade() (англ. filter first decade, «отобрать первую декаду»), 
#которая фильтрует таблицу по этому условию. 
#Функция должна получать на вход исходную таблицу и, не меняя её, возвращать отфильтрованную.
oscar_data = [
    ['Форма воды', 2017, 6.914, 123, ['фантастика', 'драма'], 19.4, 195.243464],
    ['Лунный свет', 2016, 6.151, 110, ['драма'], 1.5, 65.046687],
    ['В центре внимания', 2015, 7.489, 129, ['драма', 'криминал', 'история'], 20.0, 88.346473],
    ['Бёрдмэн', 2014, 7.604, 119, ['драма', 'комедия'], 18.0, 103.215094],
    ['12 лет рабства', 2013, 7.71, 133, ['драма', 'биография', 'история'], 20.0, 178.371993],
    ['Операция "Арго"', 2012, 7.517, 120, ['триллер', 'драма', 'биография'], 44.5, 232.324128],
    ['Артист', 2011, 7.942, 96, ['драма', 'мелодрама', 'комедия'], 15.0, 133.432856],
    ['Король говорит!', 2010, 7.977, 118, ['драма', 'биография', 'история'], 15.0, 414.211549],
    ['Повелитель бури', 2008, 7.298, 126, ['триллер', 'драма', 'военный', 'история'], 15.0, 49.230772],
    ['Миллионер из трущоб', 2008, 7.724, 120, ['драма', 'мелодрама'], 15.0, 377.910544],
    ['Старикам тут не место', 2007, 7.726, 122, ['триллер', 'драма', 'криминал'], 25.0, 171.627166],
    ['Отступники', 2006, 8.456, 151, ['триллер', 'драма', 'криминал'], 90.0, 289.847354],
    ['Столкновение', 2004, 7.896, 108, ['триллер', 'драма', 'криминал'], 6.5, 98.410061],
    ['Малышка на миллион', 2004, 8.075, 132, ['драма', 'спорт'], 30.0, 216.763646],
    ['Властелин колец: Возвращение Короля', 2003, 8.617, 201, ['фэнтези', 'драма', 'приключения'], 94.0, 1119.110941],
    ['Чикаго', 2002, 7.669, 113, ['мюзикл', 'комедия', 'криминал'], 45.0, 306.776732],
    ['Игры разума', 2001, 8.557, 135, ['драма', 'биография', 'мелодрама'], 58.0, 313.542341],
    ['Гладиатор', 2000, 8.585, 155, ['боевик', 'драма', 'приключения'], 103.0, 457.640427],
    ['Красота по-американски', 1999, 7.965, 122, ['драма'], 15.0, 356.296601],
    ['Влюбленный Шекспир', 1998, 7.452, 123, ['драма', 'мелодрама', 'комедия', 'история'], 25.0, 289.317794],
    ['Титаник', 1997, 8.369, 194, ['драма', 'мелодрама'], 200.0, 2185.372302],
    ['Английский пациент', 1996, 7.849, 155, ['драма', 'мелодрама', 'военный'], 27.0, 231.976425],
    ['Храброе сердце', 1995, 8.283, 178, ['драма', 'военный', 'биография', 'история'], 72.0, 210.409945],
    ['Форрест Гамп', 1994, 8.915, 142, ['драма', 'мелодрама'], 55.0, 677.386686],
    ['Список Шиндлера', 1993, 8.819, 195, ['драма', 'биография', 'история'], 22.0, 321.265768],
    ['Непрощенный', 1992, 7.858, 131, ['драма', 'вестерн'], 14.4, 159.157447],
    ['Молчание ягнят', 1990, 8.335, 114, ['триллер', 'криминал', 'детектив', 'драма', 'ужасы'], 19.0, 272.742922],
    ['Танцующий с волками', 1990, 8.112, 181, ['драма', 'приключения', 'вестерн'], 22.0, 424.208848],
    ['Шофёр мисс Дэйзи', 1989, 7.645, 99, ['драма'], 7.5, 145.793296],
    ['Человек дождя', 1988, 8.25, 133, ['драма'], 25.0, 354.825435],
]

def filter_first_decade(data):
    result = []
    for row in data:
        year = row[1]
        if year >= 2000 and year <= 2010:
            result.append(row)
    return result

def print_table(data):
    print('Название                            | Год  | Рейтинг | Длина | Бюджет | Сборы  |')
    print('--------------------------------------------------------------------------------')
    for row in data:
        print('{: <35} | {} | {: >7.2f} | {: >5} | {: >6.1f} | {: >6.1f} |'.format(
            row[0], row[1], row[2], row[3], row[5], row[6]))
        
filtered_data = filter_first_decade(oscar_data)
print_table(filtered_data)

# Словари

Словарь - Особая структура данных. Словарь состоит из ключа и значения:

In [ ]:
{'purchase':['count','sum']}

Здесь ключ — это название столбца, к которому нужно применить функции, а значением выступает список с названиями функций.

In [1]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "https://pictures.s3.yandex.net/resources/Frame_3.2_1561106449.jpg")

# Try-except

Исходный код помещают в блок try. Если при выполнении кода из блока try возникнет ошибка, воспроизведётся код из блока except.

In [ ]:
a = 1
b = 0
try: 
    print(a / b)
except: 
    print('Проверьте значения параметров a и b')
    print ('Кстати, хорошего дня')

In [ ]:
#Примените конструкцию try-except и обработайте ошибки, мешающие решению задачи. 
#Создайте переменную wrong_lines для подсчета некорректных строк и в except посчитайте их количество. 
#Выведите на экран общее количество строк и количество некорректных строк в формате:

position = [
['2019-05-01', '- 6'],
['2019-05-02', '+5'],
['2019-05-03', ' 5'],
['2019-05-04', '4'],
['2019-05-05', '5'],
['2019-05-06', '5'],
['2019-05-07', '4'],
['2019-05-08', 'Error 5'],
['2019-05-09', '3'],
['2019-05-10', '3'],
]
count_lines = 0
total_position = 0
wrong_lines = 0
for row in position:
    try:
        count_lines += 1
        level = int(row[1])
        total_position += level
    except:
        wrong_lines += 1
print('Количество измерений', count_lines)
print ('Количество некорректных строк', wrong_lines)

In [ ]:
#Полезно знать не только сколько ошибок, но и где они. 
#Добавьте возможность записывать строки с ошибками в список. 
#Выведите на экран общее количество строк и список некорректных строк в формате:

position = [
['2019-05-01', '- 6'],
['2019-05-02', '+5'],
['2019-05-03', ' 5'],
['2019-05-04', '4'],
['2019-05-05', '5'],
['2019-05-06', '5'],
['2019-05-07', '4'],
['2019-05-08', 'Error 5'],
['2019-05-09', '3'],
['2019-05-10', '3'],
]

total_position = 0
count_lines = 0
wrong_lines_content = []

for row in position:
    try:
        count_lines += 1
        level = int(row[1])
        total_position += level
    except:
        wrong_lines_content.append(row)
print('Количество измерений', count_lines)
print('Некорректные строки', wrong_lines_content)